export const productsInfo = {
  kolsch1: {
    id: "kolsch1",
    title: "Kölsch",
    type: "Cervezas",
    subtitle: "dorada / suave / fresca / frutada",
    desc: "Existen muchas cervezas doradas y refrescantes. Pero frutadas y con destellos finales de lúpulo, sólo hay un estilo: la Kölsch. En Antares rescatamos la antigua receta de la cerveza favorita de los bebedores en colonia, Alemania, y la honramos desde 1998. En nuestra cocina, su legado sigue intacto.",
    alcVol: "5%",
    ibu: 22,
    amargor: "2/4",
    imageURL:
      "https://firebasestorage.googleapis.com/v0/b/antaresfacu-17d20.appspot.com/o/productos%2Fcervezas%2Fkolsch_beer.png?alt=media&token=0b744a21-74d5-4983-aaa6-adc6c11662e9",
    price: 300,
  },
  scotch1: {
    id: "scotch1",
    title: "Scotch",
    type: "Cervezas",
    subtitle: "rubí / maltosa / dulce / con cuerpo",
    desc: "Escocia es tierra de cebada y la Scotch Ale lleva ese paisaje impregnado en su código genético. Rubí intenso. Seis grados de alcohol. Dulce y maltosa. La Antares más servida en nuestro Brewpub. Una fórmula a prueba del paso del tiempo.",
    alcVol: "6%",
    ibu: 18,
    amargor: "1/4",
    imageURL:
      "https://firebasestorage.googleapis.com/v0/b/antaresfacu-17d20.appspot.com/o/productos%2Fcervezas%2Fscotch_beer.png?alt=media&token=a3ed2418-6382-4541-9dbe-e996a565bcf6",
    price: 145,
  },
  porter1: {
    id: "porter1",
    title: "Porter",
    type: "Cervezas",
    subtitle: "marrón oscura / chocolate / café",
    desc: "Maltas oscuras. Sabor y aroma penetrante y nocturno. Chocolate, azúcar negro y café. La Porter es la cerveza tributo de Antares a la cultura de los primeros pubs en el puerto de Londres. Cheers.",
    alcVol: "5,5%",
    ibu: 27,
    amargor: "2/4",
    imageURL:
      "https://firebasestorage.googleapis.com/v0/b/antaresfacu-17d20.appspot.com/o/productos%2Fcervezas%2Fporter_beer.png?alt=media&token=070b0f73-9ba4-4d75-ac16-999fd65f2b35",
    price: 125,
  },
  barleywine1: {
    id: "barleywine1",
    title: "Barley Wine",
    type: "Cervezas",
    subtitle: "bronce / compleja / fuerte / corpulenta",
    desc: "Nuestra cerveza de mayor graduación alcohólica. Una hermandad de malta y licor, con rasgos de nuez, caramelo y dulce de leche. Barley Wine, cuando la vid se vuelve cebada.",
    alcVol: "10%",
    ibu: 53,
    amargor: "3/4",
    imageURL:
      "https://firebasestorage.googleapis.com/v0/b/antaresfacu-17d20.appspot.com/o/productos%2Fcervezas%2Fbarleywine_beer.png?alt=media&token=9ae135c2-7cba-415b-8263-925786b26867",
    price: 165,
  },
  parma1: {
    id: "parma1",
    title: "Parma",
    type: "Pizzas",
    subtitle: "",
    desc: "Mozzarella, jamón crudo, rúcula fresca y aceitunas negras",
    imageURL: "https://firebasestorage.googleapis.com/v0/b/antaresfacu-17d20.appspot.com/o/productos%2Fpizzas%2Fpizza_parma.jpeg?alt=media&token=e675576c-622a-4f28-aac0-b044e5756ed9",
    price: 1100,
  },
  capri1: {
    id: "capri1",
    title: "Capri",
    type: "Pizzas",
    subtitle: "",
    desc: "Mozzarella, tomate cherry, aceitunas negras, albahaca y aceite de oliva",
    imageURL: "https://firebasestorage.googleapis.com/v0/b/antaresfacu-17d20.appspot.com/o/productos%2Fpizzas%2Fpizza_caprese.jpeg?alt=media&token=72a369a0-2de0-42e1-816f-4f19648d3cb0",
    price: 1250,
  },
  americana1: {
    id: "americana1",
    title: "Americana",
    type: "Pizzas",
    subtitle: "",
    desc: "Mozzarella, panceta, morrón asado y huevo frito",
    imageURL: "https://firebasestorage.googleapis.com/v0/b/antaresfacu-17d20.appspot.com/o/productos%2Fpizzas%2Fpizza_americana.jpeg?alt=media&token=8b818ba7-0280-47b3-bbbd-c48c79701d9d",
    price: 1670,
  },
};
