export const AG_GRID_LOCALE_ES = {
  // Set Filter
  selectAll: '(Seleccionar todo)',
  selectAllSearchResults: '(Seleccionar todos los resultados de la búsqueda)',
  searchOoo: 'Buscar...',
  blanks: '(Vacíos)',
  noMatches: 'No hay coincidencias',

  // Number Filter & Text Filter
  filterOoo: 'Filtrar...',
  equals: 'Igual',
  notEqual: 'No igual',
  blank: 'Vacio',
  notBlank: 'No vacio',
  empty: 'Elegido',

  // Number Filter
  lessThan: 'Menos que',
  greaterThan: 'Mayor que',
  lessThanOrEqual: 'Menor o igual',
  greaterThanOrEqual: 'Mayor o igual',
  inRange: 'En rango',
  inRangeStart: 'Desde',
  inRangeEnd: 'Hasta',

  // Text Filter
  contains: 'Contiene',
  notContains: 'No Contiene',
  startsWith: 'Empieza con',
  endsWith: 'Termina con',

  // Date Filter
  dateFormatOoo: 'dd-mm-yyyy',

  // Filter Conditions
  andCondition: 'Y',
  orCondition: 'O',

  // Filter Buttons
  applyFilter: 'Aplicar filtro',
  resetFilter: 'Resetear filtro',
  clearFilter: 'Limpiar filtro',
  cancelFilter: 'Cancelar filtro',

  // Filter Titles
  textFilter: 'Filtro de texto',
  numberFilter: 'Filtro de número',
  dateFilter: 'Filtro de fecha',
  setFilter: 'Filtro de conjunto',

  // Side Bar
  columns: 'Columnas',
  filters: 'Filtros',

  // columns tool panel
  pivotMode: 'Modo Pivote',
  groups: 'Grupos',
  rowGroupColumnsEmptyMessage: 'Arrastre una columna para agrupar',
  values: 'Valores',
  valueColumnsEmptyMessage: 'Arrastre una columna para mostrar valores',
  pivots: 'Pivotes',
  pivotColumnsEmptyMessage: 'Arrastre una columna para mostrar pivotes',

  // Header of the Default Group Column
  group: 'Grupo',

  // Row Drag
  rowDragRows:'Filas',

  // Other
  loadingOoo: 'Cargando...',
  noRowsToShow: 'No hay filas para mostrar',
  enabled: 'Habilitado',

  // Traducir bloque
  pinColumn: 'Fijar columna',
  pinLeft: 'Pin Izquierda',
  pinRight: 'Pin Derecha',
  noPin: 'No Pin',
  valueAggregation: 'Valor de agregación',
  autosizeThiscolumn: 'Autosize esta columna',
  autosizeAllColumns: 'Autosize todas las columnas',
  groupBy: 'Agrupar por',
  ungroupBy: 'Desagrupar por',
  addToValues: 'Agregar ${variable} a valores',
  removeFromValues: 'Eliminar ${variable} de valores',
  addToLabels: 'Agregar ${variable} a etiquetas',
  removeFromLabels: 'Eliminar ${variable} de etiquetas',
  resetColumns: 'Reiniciar columnas',
  expandAll: 'Expandir todo',
  collapseAll: 'Contraer todo',
  copy: 'Copiar',
  ctrlC: 'Ctrl+C',
  copyWithHeaders: 'Copiar con encabezados',
  copyWithHeaderGroups: 'Copiar con grupos de encabezados',
  paste: 'Pegar',
  ctrlV: 'Ctrl+V',
  export: 'Exportar',
  csvExport: 'Exportar CSV',
  excelExport: 'Exportar Excel',

  // Enterprise Menu Aggregation and Status Bar
  sum: 'Suma',
  min: 'Mínimo',
  max: 'Máximo',
  none: 'Ninguno',
  count: 'Contar',
  avg: 'Promedio',
  filteredRows: 'Filas filtradas',
  selectedRows: 'Filas seleccionadas',
  totalRows: 'Filas totales',
  totalAndFilteredRows: 'Filas totales y filtradas',
  more: 'Más',
  to: 'a',
  of: 'de',
  page: 'Página',
  nextPage: 'Página siguiente',
  lastPage: 'Última página',
  firstPage: 'Primera página',
  previousPage: 'Página anterior',


  // Pivoting
  pivotColumnGroupTotals: 'Total',

  // Enterprise Menu (Charts)
  pivotChartAndPivotMode: 'Gráfico y modo pivote',
  pivotChart: 'Gráfico',
  chartRange: 'Rango de gráfico',

  columnChart: 'Gráfico de columnas',
  groupedColumn: 'Columnas agrupadas',
  stackedColumn: 'Columnas apiladas',
  normalizedColumn: 'Columnas normalizadas',

  barChart: 'Gráfico de barras',
  groupedBar: 'Barras agrupadas',
  stackedBar: 'Barras apiladas',
  normalizedBar: 'Barras normalizadas',

  pieChart: 'Gráfico circular',
  pie: 'Circular',
  doughnut: 'Torta',

  line: 'Línea',

  xyChart: 'Gráfico XY',
  scatter: 'Dispersión',
  bubble: 'Burbuja',

  areaChart: 'Gráfico de áreas',
  area: 'Área',
  stackedArea: 'Áreas apiladas',
  normalizedArea: 'Áreas normalizadas',

  histogramChart: 'Gráfico de histograma',

  combinationChart: 'Gráfico de combinación',
  columnLineCombo: 'Columnas y líneas',
  AreaColumnCombo: 'Áreas y columnas',

  // Charts
  pivotChartTitle: 'Gráfico de pivote',
  rangeChartTitle: 'Gráfico de rango',
  settings: 'Configuración',
  data: 'Datos',
  format: 'Formato',
  categories: 'Categorías',
  defaultCategory: '(sin categoría)',
  series: 'Series',
  xyValues: 'Valores XY',
  paired: 'Apareadas',
  axis: 'Eje',
  navigator: 'Navegador',
  color: 'Color',
  thickness: 'Grosor',
  xType: 'Tipo X',
  automatic: 'Automático',
  category: 'Categoría',
  number: 'Número',
  time: 'Tiempo',
  xRotation: 'Rotación X',
  yRotation: 'Rotación Y',
  ticks: 'Marcas',
  width: 'Ancho',
  height: 'Alto',
  length: 'Longitud',
  padding: 'Relleno',
  spacing: 'Espaciado',
  chart: 'Gráfico',
  title: 'Título',
  titlePlaceholder: 'Título de gráfico',
  background: 'Fondo',
  font: 'Fuente',
  top: 'Arriba',
  right: 'Derecha',
  bottom: 'Abajo',
  left: 'Izquierda',
  labels: 'Etiquetas',
  size: 'Tamaño',
  minSize: 'Tamaño mínimo',
  maxSize: 'Tamaño máximo',
  legend: 'Leyenda',
  position: 'Posición',
  markerSize: 'Tamaño de marca',
  markerStroke: 'Trazo de marca',
  markerPadding: 'Relleno de marca',
  itemSpacing: 'Espaciado de elementos',
  itemPaddingX: 'Relleno horizontal de elementos',
  itemPaddingY: 'Relleno vertical de elementos',
  layoutHorizontalSpacing: 'Espaciado horizontal de diseño',
  layoutVerticalSpacing: 'Espaciado vertical de diseño',
  strokeWidth: 'Ancho de trazo',
  offset: 'Desplazamiento',
  offsets: 'Desplazamientos',
  tooltips: 'Descripciones emergentes',
  callout: 'Llamada',
  markers: 'Marcadores',
  shadow: 'Sombra',
  blur: 'Desenfoque',
  xOffset: 'Desplazamiento X',
  yOffset: 'Desplazamiento Y',
  lineWidth: 'Ancho de línea',
  normal: 'Normal',
  bold: 'Negrita',
  italic: 'Cursiva',
  boldItalic: 'Negrita cursiva',
  predefined: 'Predefinido',
  fillOpacity: 'Opacidad de relleno',
  strokeOpacity: 'Opacidad de trazo',
  histogramBinCount: 'Número de contenedores',
  columnGroup: 'Grupo de columnas',
  barGroup: 'Grupo de barras',
  pieGroup: 'Grupo de tortas',
  lineGroup: 'Grupo de líneas',
  scatterGroup: 'Grupo de dispersión',
  areaGroup: 'Grupo de áreas',
  histogramGroup: 'Grupo de histograma',
  combinationGroup: 'Grupo de combinación',
  groupedColumnTooltip: 'Grupo de columnas',
  stackedColumnTooltip: 'Columnas apiladas',
  normalizedColumnTooltip: 'Columnas normalizadas',
  groupedBarTooltip: 'Grupo de barras',
  stackedBarTooltip: 'Barras apiladas',
  normalizedBarTooltip: 'Barras normalizadas',
  pieTooltip: 'Torta',
  doughnutTooltip: 'Rosquilla',
  lineTooltip: 'Línea',
  groupedAreaTooltip: 'Grupo de áreas',
  stackedAreaTooltip: 'Áreas apiladas',
  normalizedAreaTooltip: 'Áreas normalizadas',
  scatterTooltip: 'Dispersión',
  bubbleTooltip: 'Burbuja',
  histogramTooltip: 'Histograma',
  columnLineComboTooltip: 'Columna/línea',
  areaColumnComboTooltip: 'Área/columna',
  customComboTooltip: 'Combinación personalizada',
  noDataToChart: 'No hay datos para mostrar',
  pivotChartRequiresPivotMode: 'El gráfico de árbol de datos requiere el modo de pivot',
  chartSettingsToolbarTooltip: 'Configuración de gráfico',
  chartLinkToolbarTooltip: 'Enlace de gráfico',
  chartUnlinkToolbarTooltip: 'Desvincular gráfico',
  chartDownloadToolbarTooltip: 'Descargar gráfico',
  seriesChartType: 'Tipo de gráfico de series',
  seriesType: 'Tipo de serie',
  secondaryAxis: 'Eje secundario',

  // ARIA
  ariaHidden: 'Oculto',
  ariaVisible: 'Visible',
  ariaChecked: 'Seleccionado',
  ariaUnchecked: 'No seleccionado',
  ariaIndeterminate:'Indeterminado',
  ariaDefaultListName: 'Lista',
  ariaColumnSelectAll: 'Seleccionar todo',
  ariaInputEditor: 'Editor de entrada',
  ariaDateFilterInput: 'Filtro de fecha',
  ariaFilterList: 'Lista de filtros',
  ariaFilterInput: 'Entrada de filtro',
  ariaFilterColumnsInput: 'Entrada de filtro de columnas',
  ariaFilterValue: 'Valor de filtro',
  ariaFilterFromValue: 'Valor de filtro desde',
  ariaFilterToValue: 'Valor de filtro hasta',
  ariaFilteringOperator: 'Operador de filtrado',
  ariaColumn: 'Columna',
  ariaColumnList: 'Lista de columnas',
  ariaColumnGroup: 'Grupo de columnas',
  ariaRowSelect: 'Seleccionar fila',
  ariaRowDeselect: 'Deseleccionar fila',
  ariaRowToggleSelection: 'Alternar selección de fila',
  ariaRowSelectAll: 'Seleccionar todo',
  ariaToggleVisibility: 'Alternar visibilidad',
  ariaSearch: 'Buscar',
  ariaSearchFilterValues: 'Buscar valores de filtro',

  ariaRowGroupDropZonePanelLabel: 'Arrastre aquí para agrupar',
  ariaValuesDropZonePanelLabel: 'Arrastre aquí para agregar valores',
  ariaPivotDropZonePanelLabel: 'Arrastre aquí para agregar valores',
  ariaDropZoneColumnComponentDescription: 'Arrastre aquí para agregar columnas',
  ariaDropZoneColumnValueItemDescription: 'Arrastre aquí para agregar valores',

  // ARIA Labels for Dialogs
  ariaLabelColumnMenu: 'Menú de columnas',
  ariaLabelCellEditor: 'Editor de celda',
  ariaLabelDialog: 'Diálogo',
  ariaLabelSelectField: 'Seleccionar campo',
  ariaLabelTooltip: 'Soporte técnico',
  ariaLabelContextMenu: 'Menú de contexto',
  ariaLabelSubMenu: 'Submenú',
  ariaLabelAggregationFunction: 'Función de agregación',

  // Number Format (Status Bar, Pagination Panel)
  thousandSeparator: '.',
  decimalSeparator: ','

}
